In [1]:
import numpy as np


In [7]:
x = np.array([[13,24],[34,66]])
y = np.array([[24,55],[32,88]])
print("MATRIX1:\n",x)
print("MATRIX2:\n",y)
sum = np.add(x,y)
print("SUM OF THE MATRIX\n",sum)

MATRIX1:
 [[13 24]
 [34 66]]
MATRIX2:
 [[24 55]
 [32 88]]
SUM OF THE MATRIX
 [[ 37  79]
 [ 66 154]]


In [13]:
x = np.array([[13,24],[34,66]])
y = np.array([[24,55],[32,88]])
print("MATRIX1:\n",x)
print("MATRIX2:\n",y)
difference= np.subtract(x,y)
print("DIFFERENCE OF THE MATRIX\n",difference)

MATRIX1:
 [[13 24]
 [34 66]]
MATRIX2:
 [[24 55]
 [32 88]]
DIFFERENCE OF THE MATRIX
 [[-11 -31]
 [  2 -22]]


In [14]:
x = np.array([[13,24],[34,66]])
y = np.array([[24,55],[32,88]])
print("MATRIX1:\n",x)
print("MATRIX2:\n",y)
mul= np.dot(x,y)
print("MULTIPLICATION OF THE MATRIX\n",mul)

MATRIX1:
 [[13 24]
 [34 66]]
MATRIX2:
 [[24 55]
 [32 88]]
MULTIPLICATION OF THE MATRIX
 [[1080 2827]
 [2928 7678]]


In [15]:
x = np.array([[13,24],[34,66]])
y = np.array([[24,55],[32,88]])
print("MATRIX1:\n",x)
print("MATRIX2:\n",y)
div= np.divide(x,y)
print("DIVISION OF THE MATRIX\n",div)

MATRIX1:
 [[13 24]
 [34 66]]
MATRIX2:
 [[24 55]
 [32 88]]
DIVISION OF THE MATRIX
 [[0.54166667 0.43636364]
 [1.0625     0.75      ]]


In [17]:
x = np.array([[13,24],[34,66]])
y = np.array([[24,55],[32,88]])
print("MATRIX1:\n",x)
print("MATRIX2:\n",y)
trans= np.transpose(x)
print("TRANSPOSE OF THE MATRIX\n",trans)

MATRIX1:
 [[13 24]
 [34 66]]
MATRIX2:
 [[24 55]
 [32 88]]
TRANSPOSE OF THE MATRIX
 [[13 34]
 [24 66]]


In [18]:
x = np.array([[13,24],[34,66]])
y = np.array([[24,55],[32,88]])
print("MATRIX1:\n",x)
print("MATRIX2:\n",y)
INV= np.linalg.inv(x)
print("INVERSE OF THE MATRIX\n",INV)

MATRIX1:
 [[13 24]
 [34 66]]
MATRIX2:
 [[24 55]
 [32 88]]
INVERSE OF THE MATRIX
 [[ 1.57142857 -0.57142857]
 [-0.80952381  0.30952381]]
